// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// communities_permutation_sampling_alpha
NumericMatrix communities_permutation_sampling_alpha(NumericMatrix in_m, int repetitions);
RcppExport SEXP CNull_communities_permutation_sampling_alpha(SEXP in_mSEXP, SEXP repetitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_m(in_mSEXP);
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(communities_permutation_sampling_alpha(in_m, repetitions));
    return rcpp_result_gen;
END_RCPP
}
// communities_permutation_sampling_beta
Rcpp::List communities_permutation_sampling_beta(NumericMatrix in_m, int repetitions);
RcppExport SEXP CNull_communities_permutation_sampling_beta(SEXP in_mSEXP, SEXP repetitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_m(in_mSEXP);
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(communities_permutation_sampling_beta(in_m, repetitions));
    return rcpp_result_gen;
END_RCPP
}
// communities_permutation_sampling_beta_interleaved_matrices
NumericMatrix communities_permutation_sampling_beta_interleaved_matrices(NumericMatrix in_m, int repetitions);
RcppExport SEXP CNull_communities_permutation_sampling_beta_interleaved_matrices(SEXP in_mSEXP, SEXP repetitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_m(in_mSEXP);
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(communities_permutation_sampling_beta_interleaved_matrices(in_m, repetitions));
    return rcpp_result_gen;
END_RCPP
}
// communities_individual_based_sampling_alpha
NumericMatrix communities_individual_based_sampling_alpha(NumericMatrix in_m, int repetitions);
RcppExport SEXP CNull_communities_individual_based_sampling_alpha(SEXP in_mSEXP, SEXP repetitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_m(in_mSEXP);
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(communities_individual_based_sampling_alpha(in_m, repetitions));
    return rcpp_result_gen;
END_RCPP
}
// compute_pvalues
NumericVector compute_pvalues(NumericVector original_vals, NumericVector randomised_vals);
RcppExport SEXP CNull_compute_pvalues(SEXP original_valsSEXP, SEXP randomised_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type original_vals(original_valsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type randomised_vals(randomised_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_pvalues(original_vals, randomised_vals));
    return rcpp_result_gen;
END_RCPP
}
// communities_individual_based_sampling_beta
Rcpp::List communities_individual_based_sampling_beta(NumericMatrix in_m, int repetitions);
RcppExport SEXP CNull_communities_individual_based_sampling_beta(SEXP in_mSEXP, SEXP repetitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_m(in_mSEXP);
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(communities_individual_based_sampling_beta(in_m, repetitions));
    return rcpp_result_gen;
END_RCPP
}
// communities_individual_based_sampling_beta_interleaved_matrices
NumericMatrix communities_individual_based_sampling_beta_interleaved_matrices(NumericMatrix in_m, int repetitions);
RcppExport SEXP CNull_communities_individual_based_sampling_beta_interleaved_matrices(SEXP in_mSEXP, SEXP repetitionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_m(in_mSEXP);
    Rcpp::traits::input_parameter< int >::type repetitions(repetitionsSEXP);
    rcpp_result_gen = Rcpp::wrap(communities_individual_based_sampling_beta_interleaved_matrices(in_m, repetitions));
    return rcpp_result_gen;
END_RCPP
}
