# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

communities_permutation_sampling_alpha <- function(in_m, repetitions) {
    .Call('CNull_communities_permutation_sampling_alpha', PACKAGE = 'CNull', in_m, repetitions)
}

communities_permutation_sampling_beta <- function(in_m, repetitions) {
    .Call('CNull_communities_permutation_sampling_beta', PACKAGE = 'CNull', in_m, repetitions)
}

communities_permutation_sampling_beta_interleaved_matrices <- function(in_m, repetitions) {
    .Call('CNull_communities_permutation_sampling_beta_interleaved_matrices', PACKAGE = 'CNull', in_m, repetitions)
}

communities_individual_based_sampling_alpha <- function(in_m, repetitions) {
    .Call('CNull_communities_individual_based_sampling_alpha', PACKAGE = 'CNull', in_m, repetitions)
}

compute_pvalues <- function(original_vals, randomised_vals) {
    .Call('CNull_compute_pvalues', PACKAGE = 'CNull', original_vals, randomised_vals)
}

communities_individual_based_sampling_beta <- function(in_m, repetitions) {
    .Call('CNull_communities_individual_based_sampling_beta', PACKAGE = 'CNull', in_m, repetitions)
}

communities_individual_based_sampling_beta_interleaved_matrices <- function(in_m, repetitions) {
    .Call('CNull_communities_individual_based_sampling_beta_interleaved_matrices', PACKAGE = 'CNull', in_m, repetitions)
}

